default:
  tags:
    - WACC

build-job:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  script:
    - mvn clean
    - mvn compile

test-job:
  stage: test
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  script:
    - mvn package -DskipTests
    - mvn test

#syntactic-test-job:
#  stage: test
#  rules:
#    - if: '$CI_COMMIT_REF_NAME == "master"'
#    - when: manual
#  script:
#    - mvn package -DskipTests
#    - mvn test -Dtest=SyntacticTests
#
#semantic-test-job:
#  stage: test
#  rules:
#    - if: '$CI_COMMIT_REF_NAME == "master"'
#    - when: manual
#  script:
#    - mvn package -DskipTests
#    - mvn test -Dtest=SemanticTests
